### PR TITLE
Lab 2 - EZGaz Requirements

### PR DESCRIPTION
**Pull request by 3aglew0**

### CODE REVIEW

**Comment by lucaardito** [comment]
There is already a REQ_s274148. Did you do the pull request twice?

**Comment by 3aglew0** [comment]
Dear professor, I worked with Giovanni Brignone He forked from SoftengPoliTo/Lab2 and I forked from him (brigio345/Lab2).When we finished the work, I renamed the file with my matricula (from REQ_s274148 to REQ_s272609) and asked for a pull request to your repository. Did I do something wrong? If you received REQ_s274148 also from me maybe I did the pull request without the last commit (that changed the file name), but it seems strange… Please let me know if I have to do another pull request, thank you. Regards,Noemi Daniele Inviato da Posta per Windows 10 Da: Luca ArditoInviato: lunedì 30 marzo 2020 15:21A: SoftengPoliTo/Lab2Cc: noemidaniele; AuthorOggetto: Re: [SoftengPoliTo/Lab2] Lab 2 - EZGaz Requirements (#42) There is already a REQ_s274148. Did you do the pull request twice?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  
	
      
		Mail priva di virus. www.avast.com

**Comment by lucaardito** [comment]
Did you do a pull request from your repo to brignone's repo? If yes, when he did his pull request, he delivered your work too.

**Comment by 3aglew0** [comment]
Yes, I did more pull requests to Brignone’s repo while we were working, but after the rename of the file I only did the pull request towards your repository.In any case, Brignone did the pull request, the only difference between our two pull requests is the name of the file, while the content is exactly the same. Inviato da Posta per Windows 10 Da: Luca ArditoInviato: lunedì 30 marzo 2020 17:21A: SoftengPoliTo/Lab2Cc: noemidaniele; AuthorOggetto: Re: [SoftengPoliTo/Lab2] Lab 2 - EZGaz Requirements (#42) Did you do a pull request from your repo to brignone's repo? If yes, when he did his pull request, he delivered your work too.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  
	
      
		Mail priva di virus. www.avast.com

**Comment by lucaardito** [comment]
In the repo there is this file: https://github.com/SoftengPoliTo/Lab2/blob/master/REQ_s274148.md

**Pull request closed without merging**
